### ISSUE TITLE
Fix Vue warning

### ISSUE THREAD

**Issue by edwh** [Freegle/iznik-nuxt3#19]
The page for a message (e.g. `/message/100028899`) has a vue warning in dev.

![image](https://github.com/Freegle/iznik-nuxt3/assets/56696/392174e1-9bb0-4a45-874c-8f226057e1f5)

These are a bit fiddly to diagnose; often caused by doing a watch on something you shouldn't.  See if you can diagnose it; stop if it takes more than a couple of hours.

**Comment by misterpekert** [comment]
@edwh, it seems this issue is not reproducible anymore. I reset the repo to the state when this issue was created (01.09.2023), and the error was constantly reproducing on the /message/[id] page. But with the actual `master` on that page, this warning doesn't appear. I've also checked the usage of `watch` and found nothing suspicious. So, I'd close it unless you know other places/scenarios where this warning appears.
