### ISSUE TITLE
Ads sometimes overlap modal contents

### ISSUE THREAD

**Issue by edwh** [Freegle/iznik-nuxt3#21]
We want our sidebar ads to be visible when modals are active.  But at some screen sizes, the ads overlap modal content:

![image](https://github.com/Freegle/iznik-nuxt3/assets/56696/5a6c7130-fb90-498a-94fb-530fbb3782b7)

Ideally the ad would appear above the modal fade and below the modal content, so that if there was any overlap, it was the ad which got hidden.

I've had a quick attempt to fix this and failed.  I think this is because of the way that the z-index of a parent restricts the z-index of a child.  This means I can't set the z-index on the ads to appear between the modal and the modal fade.

Can you have a look at this to see if I'm missing something, and think about any other solutions?  We are limited by Bootstrap here, but perhaps we could disable the bootstrap modal fade and add our own one, which would give us more freedom to mess with z-index.  

We can live with this if we need to, though, so it's not worth too much effort.

**Comment by smellyshovel** [comment]
Most probably that isn't going to work neither way.

Both elements (ads and backdrops/modals) are on different levels in the DOM (they are not related anyhow). That means that for both of them 2 different stacking contexts are created, and one can only control z-indexes of the same stacking context.

On the other hand, there may be a solution if we wrap the ads in a conditional teleport. So that if there's an open modal, we'd "teleport" the ad over its backdrop. However, I'm not sure how to track whether there's a modal opened at all or not. We can check all the modals-related flags of a given component, but that seems to me an overkill.

Would you like me to try that solution?

A good reading on the topic: https://www.joshwcomeau.com/css/stacking-contexts/#a-common-misconception-about-z-index-4

**Comment by edwh** [comment]
I wondered about teleport. I've not used it.

I think you can globally listen for any modal opening/closing.

https://bootstrap-vue.org/docs/components/modal#comp-ref-b-modal-rootEventListeners

This isn't quite ideal because it probably means that the ad will be destroyed and then recreated.  That isn't great for ad visibility - ads need to be shown for a period of time to be counted as a view.  

Maybe we could have our own modal component instead of `b-modal`.  We could use the same template/slot names, and then wrap the body inside a teleport?

**Comment by edwh** [comment]
This may be easier to do now that modals have been reworked to use `useModal`.

**Comment by edwh** [comment]
@misterpekert Worth highlighting that I want to avoid the ads being deleted and recreated when a modal opens/closes.  That would damage their "viewability" - an ad has to be viewable for a period of time before being counted as a view for payment.

**Comment by misterpekert** [comment]
Yeah, sure

**Comment by misterpekert** [comment]
@edwh I've added the event to track the visibility of ad slot (#46)

I think we can have some custom Sentry error (or any other way of gathering analytics) in case visibility of add drops below 50%. I can also try implementing custom backdrop, but it seems to be a bit of overkill :)

Ideally, I'd propose to have a separate advertisement slot inside the modal, so we would also cover those users who don't have ads left and right due to the small screen size.

**Comment by misterpekert** [comment]
@edwh I think we can close this one. As far as I remember, we ended up just having an advertisement container under the backdrop of a modal, which seems to be fine with Google :)
