### ISSUE TITLE
Improve ask for postcode/phone number

### ISSUE THREAD

**Issue by edwh** [Freegle/iznik-nuxt3#4]
Currently we ask for these when people are replying:

![image](https://github.com/Freegle/iznik-nuxt3/assets/56696/9ed1b5e5-3820-4742-a686-6902579d5996)

The text below the phone number box is quite subtle, so sometimes people don't read it and therefore think their phone number would be passed on. They might therefore either be reluctant to provide it or get confused when asked for a phone number later.

We want to:

1. Remove that box from there
2. Let them reply
3. After replying, do a popup which asks for their postcode and phone number, explaining why.

**Comment by smellyshovel** [comment]
Slightly not clear. First you only mention the phone number box, but then, under the 3rd point, you say that you want to move both the fields into a separate modal. Both the phone number and the postcode. For me it seems like it'd be possible to do that for the phone number, but regarding the postcode, I wouldn't be that sure: I think I saw it being passed together with some API request which is performed when the button to reply is pressed. Therefore, it might be necessary in order to reply. But I'm not sure.

**Comment by edwh** [comment]
Both phone number and postcode please.

I think they can both be moved.  If you look in `MessageReplySection` at `SavePostcode`, and the `SettingsPhone` component, then they are both independent of the actual reply processing in `sendReply`.  They make separate API calls.  So they can be made later.
