### ISSUE TITLE
ChitChat and mobile navbar

### ISSUE THREAD

**Issue by edwh** [Freegle/iznik-nuxt3#65]
The mobile navbar fades away when you scroll up, then comes back either when you scroll down or after a delay.  This can mean that if you're on ChitChat and replying to a post, then the navbar can pop up over the box you're typing in.  

It's possible this problem exists in other places I've not noticed, so something that fixed it in the navbar would be ideal.  For example, could we scroll the window up by the navbar height when the navbar is visible?

This would need testing on real Android and IOS devices using Browserstack, because real mobile keyboards behave differently from the browser emulators.

**Comment by untael** [comment]
The bad scenarious I see in scope of that issue is:

1. User focusing some inputs at the top of the screen that potentially can be overlapped by TOP navbar
2. User focusing some inputs at the bottom of the screen that potentially can be overlapped by BOTTOM navbar

Fixing that by additional scrolling focused inputs to the user viewport can potentially reduce the performance and may be costful in implementation prospective.

My suggestions here is:

1. To make bottom navbar static but rethink its UX to make it more friendly to the customer (its a common practise)
2. To collapse BOTTOM navbar to its compact version with special controls to expand it back to normal size if needed.

Also I noticed that we have a lot of not needed calls to handle scroll in Mobile Navbar component that can be easily omitted by using debounce.

**Comment by edwh** [comment]
1. The reason for removing the navbar is for screen space.  If you're on a page where you're short of screen space, making the navbar move useful just makes it easier for you to navigate away from that page.  It doesn't help you have more useful screen space on that page.  But maybe I misunderstand you.
2. I think the same problem would arise if you had controls to expand the navbar - it might still expand over the input box you're typing in.  And we know we have users who won't notice/understand navbar controls, which is why it comes back after a delay when you do nothing.  The point is that whatever method we use to decide when to show/hide the navbar, when it is shown it shouldn't overlap something you're currently working in.

I think what we need is something similar to the changes I made in `LayoutCommon` for `marginTop`, but for the bottom.

It might be possible to use debounce.  But I worry that if we did that, we could end up getting stuck in the wrong state.  For example if we scroll down and up very quickly, we might only call `handleScroll` for the up case and not the down case, which would result in the wrong behaviour.  I don't think adding debounce would solve any real problems, and it might create some.  So let's not.
